[package]
name = "ssh-agent"
description = "Library for implementing an SSH agent"
version = "0.2.0"
license = "MIT"
authors = [
    "Nicolas Trippar <ntrippar@gmail.com>",
    "Federico Pomar <fmpomar@users.noreply.github.com>"
]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "sekey/ssh-agent.rs" }
codecov = { repository = "sekey/ssh-agent.rs" }

[dependencies]
byteorder = "1.2.7"
num-traits = "0.2"
serde = "1.0.87"
serde_derive = "1.0.87"
bytes = "0.4.11"
tokio = "0.1.15"
tokio-uds = "0.2.5"
futures = "0.1.25"
log = "0.4.6"

[dev-dependencies]
env_logger = "0.6.0"
openssl = "0.10.16"
